"""
Rule engine: validates Gemma's rule picks, adds deterministic hits, sets the final
verdict, and attaches citations from the curated statute list. No citation is
ever generated by the model.
"""
from __future__ import annotations

import json
import re

from config import DATA
from redact import normalize_digits

_rules_doc = json.loads((DATA / "rules.json").read_text(encoding="utf-8"))
_stat_doc = json.loads((DATA / "statutes.json").read_text(encoding="utf-8"))

RULES: dict[str, dict] = {r["id"]: r for r in _rules_doc["rules"]}
STATUTES: dict[str, dict] = {s["id"]: s for s in _stat_doc["statutes"]}
HELP: list[dict] = _stat_doc.get("help", [])

CATEGORIES = [
    "late_fee", "processing_fee", "interest_rate", "unilateral_change", "repossession",
    "rights_waiver", "prepayment", "security_deposit", "eviction", "other",
]
VERDICTS = ["OK", "CAREFUL", "NOT_OK"]
_RANK = {"OK": 0, "CAREFUL": 1, "NOT_OK": 2}

# Rules the model may choose. Doc-level rules are computed by code only.
MODEL_RULE_IDS = [rid for rid, r in RULES.items() if not r.get("doc_level")]

_COMPOUND = re.compile(
    r"compound|capitali[sz]|interest on (?:the )?(?:overdue|unpaid|penal|delayed)|penal interest|"
    r"additional interest|default interest|সুদের উপর সুদ|চক্রবৃদ্ধি|ब्याज पर ब्याज|चक्रवृद्धि",
    re.I,
)
_LATE = re.compile(r"late|delay|overdue|default|penal|বিলম্ব|দেরি|বকেয়া|विलंब|देरी|बकाया", re.I)
_BLANK = re.compile(
    r"(?:blank|undated|unfilled|ফাঁকা|সাদা|খালি|खाली|कोरा|कोरे|कोरी|बिना तारीख)\s*\S{0,12}\s*"
    r"(?:cheque|check|stamp|paper|page|document|চেক|স্ট্যাম্প|কাগজ|পাতা|चेक|स्टांप|कागज़|कागज|पन्न)",
    re.I,
)
_FLAT = re.compile(r"\bflat\b|ফ্ল্যাট|फ्लैट", re.I)
_INTEREST = re.compile(r"interest|\brate\b|সুদ|ब्याज", re.I)
_APR = re.compile(
    r"\bAPR\b|annual percentage rate|key facts? statement|\bKFS\b|বার্ষিক শতাংশ হার|वार्षिक प्रतिशत दर",
    re.I,
)


def rule_list_for_prompt() -> str:
    return "\n".join(f"- {rid}: {RULES[rid]['model_hint']}" for rid in MODEL_RULE_IDS)


def clause_deterministic_hits(text: str) -> list[str]:
    """Pattern-based hits that do not depend on the model."""
    t = normalize_digits(text)
    hits = []
    if _COMPOUND.search(t) and _LATE.search(t):
        hits.append("penal_compounding")
    if _BLANK.search(t):
        hits.append("blank_documents")
    # "flat" alone can mean an apartment; require an interest word nearby.
    if _FLAT.search(t) and _INTEREST.search(t):
        hits.append("flat_rate_presented")
    return hits


def doc_level_hits(full_text: str, terms: dict | None, money: dict | None) -> list[dict]:
    """
    Whole-document checks. Returns [{"rule_id", "detail"}].
    """
    hits = []
    terms = terms or {}
    doc_type = terms.get("doc_type") or "loan"

    if money and money.get("stated_annual_pct") is not None:
        stated, apr = money["stated_annual_pct"], money["apr_pct"]
        # A gap of a few points is rounding or a small fee; flag clear gaps only.
        if apr - stated >= max(3.0, 0.2 * stated):
            hits.append({"rule_id": "effective_cost_mismatch",
                         "detail": {"stated_annual_pct": stated, "apr_pct": apr}})

    if doc_type == "loan" and not _APR.search(full_text):
        hits.append({"rule_id": "missing_apr_disclosure", "detail": {}})

    rent, dep = terms.get("monthly_rent"), terms.get("security_deposit")
    if rent and dep and dep > 2 * rent:
        hits.append({"rule_id": "excessive_security_deposit",
                     "detail": {"monthly_rent": rent, "security_deposit": dep, "months": round(dep / rent, 1)}})
    return hits


def attach_doc_hits(clauses: list[dict], hits: list[dict],
                    primary: dict[int, str] | None = None) -> tuple[dict[int, list[str]], list[str]]:
    """
    Pin each doc-level hit to the most relevant clause: one whose main category is
    the rule's first category, then its other categories; analysed clauses first.
    A clause that merely mentions "interest" (e.g. a late-fee clause) loses to one
    that is mainly about interest. Hits with no matching clause stay document-wide.
    """
    primary = primary or {}
    per_clause: dict[int, list[str]] = {}
    unattached: list[str] = []
    for h in hits:
        cats = RULES[h["rule_id"]]["categories"]

        def key(c: dict) -> tuple:
            p = primary.get(c["id"])
            return (cats.index(p) if p in cats else len(cats), not c["selected"], -c["score"])

        pool = sorted((c for c in clauses if set(cats) & set(c["categories"]) or primary.get(c["id"]) in cats), key=key)
        target = pool[0] if pool else None
        if target is None:
            unattached.append(h["rule_id"])
        else:
            per_clause.setdefault(target["id"], []).append(h["rule_id"])
    return per_clause, unattached


def finalize(analysis: dict | None, clause_text: str, extra_rule_ids: list[str] | None = None) -> dict:
    """
    Combine the model's analysis with code checks.
    - Drops any rule id not in the curated list.
    - The final verdict is the worse of the model verdict and the worst rule hit;
      rules can raise a verdict, never lower it.
    """
    model_ids = [r for r in (analysis or {}).get("rule_ids", []) if r in RULES and not RULES[r].get("doc_level")]
    code_ids = clause_deterministic_hits(clause_text) + list(extra_rule_ids or [])
    rule_ids = list(dict.fromkeys(model_ids + code_ids))

    model_verdict = (analysis or {}).get("verdict")
    if model_verdict not in _RANK:
        model_verdict = None

    def severity(r: str) -> str:
        # The model saying "OK" while tagging a rule is self-contradictory: such a tag can
        # raise the verdict only to CAREFUL. Rules found by code always apply in full.
        s = RULES[r]["severity"]
        if r in model_ids and r not in code_ids and model_verdict == "OK" and s == "NOT_OK":
            return "CAREFUL"
        return s

    rule_verdict = max((severity(r) for r in rule_ids), key=_RANK.get, default=None)
    candidates = [v for v in (model_verdict, rule_verdict) if v]
    verdict = max(candidates, key=_RANK.get) if candidates else "CAREFUL"

    if model_verdict and rule_verdict and _RANK[rule_verdict] > _RANK[model_verdict]:
        source = "raised_by_rules"
    elif model_verdict:
        source = "model" if not rule_ids else "model_and_rules"
    else:
        source = "rules"

    statute_ids = list(dict.fromkeys(s for r in rule_ids for s in RULES[r]["statute_ids"]))
    return {
        "verdict": verdict,
        "verdict_source": source,
        "rule_ids": rule_ids,
        "rule_ids_from_model": model_ids,
        "rule_ids_from_code": [r for r in rule_ids if r not in model_ids],
        "statute_ids": statute_ids,
    }


def rule_view(rule_id: str, lang: str) -> dict:
    r = RULES[rule_id]
    return {
        "id": rule_id,
        "name": r["name"].get(lang) or r["name"]["en"],
        "plain": r["plain"].get(lang) or r["plain"]["en"],
        "severity": r["severity"],
    }


def statute_view(statute_id: str, lang: str) -> dict:
    s = STATUTES[statute_id]
    return {
        "id": statute_id,
        "name": s["name"],
        "plain_summary": s["plain_summary"].get(lang) or s["plain_summary"]["en"],
        "source_url": s["source_url"],
        "source_hint": s.get("source_hint"),
        "last_verified": s.get("last_verified"),
        "verified_by": s.get("verified_by"),
    }


def help_view(lang: str) -> list[dict]:
    return [{"id": h["id"], "name": h["name"].get(lang) or h["name"]["en"],
             "contact": h["contact"], "source_url": h["source_url"],
             "last_verified": h.get("last_verified")} for h in HELP]
